apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: jen-emp
  labels:
    app: jen-emp
spec:
  selector:
    matchLabels:
      app: jen-emp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jen-emp
    spec:
      containers:
      - image: jenkins/jenkins
        name: jen-emp
        ports:
        - containerPort: 8080
          name: jen-emp
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
      volumes:
      - name: jenkins-home
        emptyDir: {}


